POST http://localhost:5000/api/images/upload
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTAxNWU4ODY0MGI1Y2Y5N2NiNzdhYyIsInVzZXJuYW1lIjoibmljbyIsImlhdCI6MTczNzQ5NjU2NywiZXhwIjoxNzM3NTAwMTY3fQ.RTE8xBzqnIfilDV4ScJyn8bDlhE-B_6I3sNUN0wzVNE

--boundary
Content-Disposition: form-data; name="image"; filename="test.jpg"

< th-removebg.png 
--boundary--

### getallimages
GET http://localhost:5000/api/images
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTAxNWU4ODY0MGI1Y2Y5N2NiNzdhYyIsInVzZXJuYW1lIjoibmljbyIsImlhdCI6MTczNzQ5NjU2NywiZXhwIjoxNzM3NTAwMTY3fQ.RTE8xBzqnIfilDV4ScJyn8bDlhE-B_6I3sNUN0wzVNE

### getimageid
GET http://localhost:5000/api/images/678eb04b0a2f09279b9568a0

### deleteimage
DELETE http://localhost:5000/api/images/678eb04b0a2f09279b9568a0

### resizeimage
GET http://localhost:5000/api/images/resize/678eb13827c2f05255ee871?width=400&height=400

### rotateimage
GET http://localhost:5000/api/images/rotate/678eb13827c2f05255ee8712?angle=90

###flipImage
GET http://localhost:5000/api/images/flip/678eb13827c2f05255ee8712?flip=horizontal

###changeformat
GET http://localhost:5000/api/images/change/678eb13827c2f05255ee8712?format=jpeg